### ISSUE TITLE
cannot add to cart products after updating ps_eventbus to v3.0.7

### ISSUE THREAD

**Issue by bluegifts** [PrestaShopCorp/ps_eventbus#277] opened 2024-04-12 11:29 UTC
cannot add to cart products after updating ps_eventbus to v3.0.7
prestashop 8.1.5 with php 8.1

**Comment by bluegifts** [comment] 2024-04-12 12:07
when i disable the module works great. bluegifts.ro website.

**Comment by jokesterfr** [comment] 2024-04-15 11:56
Hi @bluegifts,
thank you for the issue, we will investigate more on this soon.
Do you have any log in the PHP server error log?

**Comment by jokesterfr** [comment] 2024-04-16 07:55
@bluegifts just getting back to you, as this issue is unexpected and could possibly impact other merchants as well.

Adding carts is calling a hook, and this operation should not fail. We cannot reproduce your issue locally with our test environments.

Could you provide us some error logs? An access to a staging environment to reproduce the issue?

You can reach me directly by email: clement.desiles@prestashop.com, or via our Support Team. 
Thank you,

**Comment by fox-john** [comment] 2024-04-18 12:44
Hello @bluegifts,

We have release a [new version](https://github.com/PrestaShopCorp/ps_eventbus/releases/tag/v3.0.8) of Ps_Eventbus. Can you update your Ps_Eventbus to 3.0.8. on your shop, and say me if your problem persist ?

**Comment by fox-john** [comment] 2024-05-14 09:22
We haven't received a response regarding this issue for one month, so we're closing it.

Should the problem persist, please feel free to reach out to us again or contact support directly.

**Closed by fox-john** 2024-05-14 09:22 UTC
Labels: 🐛 Bug
